import styles from "@/components/homepage/Home.module.css";
const Seocontent=()=>{
    return(
        <>
        <div className={styles.seoContainer}>
         <h5>Send Fresh Flowers Cakes Online with Giftlaya- India’s Top Gifting Website</h5>
         <p>Thinking of sending flowers to your loved ones living in another city? Trust us it’s not an issue anymore. Giftlaya is made with a motto of binding all your close ones with love, care, and happiness because Fresh Flowers, Cakes, and gifts are synonymous with everything that is good and fun. Now, distance will not hamper your Birthday Celebration with your partner, because you can easily send cakes online at any part of India with Giftlaya. Even if you forgot your anniversary and don’t want to upset your wife you can order from Giftlaya and buy flowers as we provide same-day delivery and midnight delivery as well. </p>
         <h6>Buy Flowers, Cakes, and Gifts at One Place Giftlaya </h6>
         <p>While ordering from an online store customers often face the problem of buying three different things from three different places. It’s not only a hassle but also costs extra delivery charges. Giftlaya is the one-stop destination that provides cakes, lots of gift options to choose from, and flower delivery online. On our website, you will get everything from fresh flowers to personalized gifts all in one store. And on top of that buy a flower bouquet starting from Rs 299 with free delivery. </p>
         <p>All of our celebrations and joyful holiday, events include gifts. The best website to shop for online gifts is Giftlaya, which has a huge selection of presents for both men and women and for all of your important occasions. Buy online gifts for her from our incredible selection of flower bouquets, chocolate baskets, designer cakes, spa supplies, cosmetics hampers, jewelry items, purses, soft toys, etc. to surprise the lovely and precious girls and women in your life. Our selection of gifts for men also includes common gifts like a belt and wallet, personalized mugs and chocolates, a basket or tray of dried fruits, personalized phone covers, a lamp, sunglasses, and a grooming package with products like beard oil, face wash, and shampoo.</p>
         <p>As Giftlaya offers online gift delivery in 200+ cities, you can avail of same-day, midnight, and next-day delivery services to deliver these presents to your loved ones without any problem. Be it a Birthday, Anniversary, Wedding, or just a small token of love buy gifts online for any occasion and for anyone. Giftlaya provides wonderful gift options to choose from, check our website and share love and happiness with your loved ones by sending their favorite gifts from us. </p>
         <h6>Buy Handpicked Gifts Online for Birthday Anniversary Baby Shower</h6>
         <p>Are you looking for some trending birthday gift ideas? Giftlaya has more than 50000+ Birthday Gift options on our website. Select from a wide range of options from Birthday Gifts for men to Gifts for wives you can buy gifts online on Giftlaya. Our Vendors are well-trusted and have lots of Options. We are one of the best Gifting websites online available in India.</p>
         <h6>Same Day Delivery anywhere in India </h6>
         <p>Giftlaya offers a wide range of delicious birthday cakes, flowers for anniversaries, birthdays, and for special occasions, and gifts for wonderful celebrations. Make your partner feel on Cloud Nine with the art of our charming Rose Bouquet, appetizing cake delivery online, and exciting gifts. Whether you and your special one live in different parts of India we provide same-day flower delivery anywhere in the country. So, even if you forgot to order flowers and cakes for the celebration you can order on that same day, and your flowers will reach your doorstep delivery fresh and ready. </p>
         <h6>Balloon Decoration with Giftlaya </h6>
         <p>Balloon Decoration is a must if you want to celebrate any occasion with a blast. Be it a Birthday, Anniversary, Baby Shower, Bridal shower, or Proposal. A homemade simple balloon decoration for a birthday can level up any place and take the decoration to a different level. You do not need lots of expensive tools or party elements, just a few colorful balloons will make a perfect balloon decoration on the wall for a birthday. Just add a few number foils, and name foils to glam up the place. But if you are scared and new to decoration just book from Giftlaya and enjoy your day. </p>
         <h6>Balloon Decoration for Birthday</h6>
         <p>Book your Birthday Decoration from Giftlaya and let us help you celebrate your most fun birthday party of. From simple happy birthday decoration to premium decoration, stage balloon decoration, and theme balloon decoration we decorate as per your liking and budget. Our simple birthday decoration starts from Rs 1499 only. Check our website Giftlaya and you will find a bunch of decoration options to choose from. Everything is curated for every special occasion. Book directly from the options or customize according to your choice and liking. </p>
         <h6>Fresh Flower Bouquet Delivery at Your Doorstep from @299 only</h6>
         <p>Flowers unquestionably make people smile, add warmth and happiness to your day, and give your spirit a peaceful, friendly feeling. Flower Delivery have the ability to express your true feelings when words fail to do so. Giftlaya is regarded as India’s top website for online flower delivery when you want to send flowers to your loved one's home. You will get fresh quality premium flowers like red roses, lilies, orchids, gerberas, carnations, Red Rose Bouquet, birthday bouquets of flowers, and lots of other flowers. Every flower and color holds a special meaning. Send flowers to your near and dear ones to shower love, to show sympathy, to congratulate, or to celebrate. </p>
         <p>Giftlaya one of the best flower delivery websites provides online flower and bouquet delivery across India and currently delivering in 200+ cities across India. Now, you can buy and buy flower bouquets under 500 from our website anywhere and anytime with the help of our super-fast and secure delivery services. The best part about Giftlaya is that our services are available at a nominal cost, for example, fresh flowers start from Rs 299 hence you don't have to dig a hole in your pocket to buy flowers online in India.</p>
         <h6>Order freshly baked theme-based cake online from Giftlaya </h6>
         <p>A celebration is incomplete without some sweetness and for that reason, Giftlaya provides online cake delivery for every occasion like birthdays, Kids' 1st Birthdays, anniversaries, Baby showers, Bride-to-be celebrations, Engagement, Weddings, and career success parties. Many of us unfortunately fail to attend our special person’s Birthday but that does not mean you cannot send yummy cakes and gifts for that person. Giftlaya is here to rescue you. </p>
         <p>Our delicious lip-smacking range of online cakes includes chocolate cake, red velvet cake, black forest cake, white forest cake, layer cake, barbie cake, eggless chocolate cake, fruit cake, ice cream cake, chocolate truffle cake, pineapple cake, rainbow cake, plum cake, photo cake, theme cakes, minion cakes, red heart anniversary cakes, special wedding cake, strawberry cake, butterscotch cake, barbie doll princess cakes, doll cakes, princess cake, marriage anniversary cake, mickey mouse cake, Chota Bheem cake, spiderman cake, heart-shaped cake, pastry cake and many more. Some of the most amazing online cake deliveries are banana cake, carrot cake, sponge cake, biscuit cake, choco lava cake, and Longines cake. Giftlaya also offers deals on both eggless cakes and as well as egg-based cakes. If you are searching to order eggless cake online in India, then Giftlaya is your one-stop destination. So, explore our wide range of cakes and buy cakes online to get the fastest delivery. </p>
         <h5>Frequently Asked Question </h5>
         <h6>Does your website offer same day flower delivery online? </h6>
         <p>Yes Giftlaya provides same day doorstep delivery for fresh flowers. We provide fresh flowers in 200+ cities. If you order fresh flowers from us, your flowers will be delivered to your doorstep on the same day. Select from fresh Red Rose Bouquet to Exotic Lilies for Birthdays Anniversary and other occasions.</p>
         <h6>Is Midnight delivery available for cakes? </h6>
         <p>If it’s your birthday or you want to surprise your loved ones at 12 am, Giftlaya has got your back. We provide delicious cake and fresh flowers in same-day and midnight delivery. </p>
         <h6>Can I send Flowers Online to other cities? </h6>
         <p>Yes you can send Fresh Flowers online on Giftlaya starting from Rs 299 only. You will get premium quality Roses, Orchids, Lilies, Gerberas, and exotic flowers at our website. </p>
         <h6>How can I order a personalized photo cake from Giftlaya?</h6>
         <p>If you want to order a personalize photo cake, photo cake from our website you have to upload your photo in our website. You will find photo uploading option on our photo cakes. </p>
         <h6>How to Order eggless cake online from Giftlaya? </h6>
         <p>Yes we do provide egg less cakes for all our customers. All you have to do is check our website and choose for eggless option and order from your favourite design. We have lots of eggless cakes option like chocolate eggless cake, Special Eggless cakes for pure vegeterians.</p>
         <h6>Does Giftlaya provide Sugar free cake? </h6>
         <p>Yes! Giftlaya do provide sugar free cake for all our health conscious customers. All you have to do is check our website and search for sugar free cakes and order from your favourite design. </p>
         <h6>How many days before should we book for Balloon decoration? </h6>
         <p>Giftlaya provides same day balloon decoration delivery for every occasion. But for 100% confirm booking we recommend 1 day prior booking for the special occasion. As booking confirmation depends on availability of slots.</p>
         <h6>Can we book balloon decoration for Birthday? </h6>
         <p>Yes! We do provide balloon decoration for your every special occasion. Giftlaya provides balloon decoration for Birthday, Anniversary, Baby shower, Bridal shower, Proposal, welcome baby, Wedding Night, Kid’s Birthday, Office Decoration, terrace decoration, Oyo Room Decoration and a lot more. Check our website for more information. </p>
         <h6>Can we buy Gifts Online for Parents? </h6>
         <p>Apart from fresh flowers, cake, plants we have variety of gifts to choose from. You can choose Gift for him, gifts for her, Birthday gifts, anniversary gifts, customized gifts and lots of other gifts available for everyone. Giftlaya offers 1000+ unique Birthday Gifts Online, or anniversary gifts for parents. Everything is available in just one click.</p>
         <h6>Can we buy flowers and chocolates combo together?</h6>
         <p>Yes you can buy fresh flowers and chocolates together from Giftlaya. We also have flower chocolate bouquet, Flower chocolate combo available at our website. </p>
        </div>
        </>
    )
}
export default Seocontent;